import { type Notification as NType } from "@prisma/client";

export const data: NType[] = [
  {
    id: "1",
    sent: new Date(),
    body: "",
    opened: new Date(),
    status: "sealed",
    title: "New Order from Aliko Dangote",
    type: "order",
    rid: "",
  },
  {
    id: "2",
    sent: new Date(),
    body: "",
    opened: new Date(),
    status: "opened",
    title: "New Order from Aliko Dangote",
    type: "order",
    rid: "",
  },
  {
    id: "3",
    sent: new Date(),
    body: "",
    opened: new Date(),
    status: "sealed",
    title: "New Order from Aliko Dangote",
    type: "order",
    rid: "",
  },
  {
    id: "4",
    sent: new Date(),
    body: "",
    opened: new Date(),
    status: "opened",
    title: "New Order from Aliko Dangote",
    type: "order",
    rid: "",
  },
  {
    id: "5",
    sent: new Date(),
    body: "",
    opened: new Date(),
    status: "sealed",
    title: "New Order from Aliko Dangote",
    type: "order",
    rid: "",
  },
  {
    id: "6",
    sent: new Date(),
    body: "",
    opened: new Date(),
    status: "opened",
    title: "New Order from Aliko Dangote",
    type: "order",
    rid: "",
  },
  {
    id: "7",
    sent: new Date(),
    body: "",
    opened: new Date(),
    status: "sealed",
    title: "New Order from Aliko Dangote",
    type: "order",
    rid: "",
  },
  {
    id: "8",
    sent: new Date(),
    body: "",
    opened: new Date(),
    status: "opened",
    title: "New Order from Aliko Dangote",
    type: "order",
    rid: "",
  },
  {
    id: "9",
    sent: new Date(),
    body: "",
    opened: new Date(),
    status: "sealed",
    title: "New Order from Aliko Dangote",
    type: "order",
    rid: "",
  },
  {
    id: "10",
    sent: new Date(),
    body: "",
    opened: new Date(),
    status: "opened",
    title: "New Order from Aliko Dangote",
    type: "order",
    rid: "",
  },
  {
    id: "11",
    sent: new Date(),
    body: "",
    opened: new Date(),
    status: "sealed",
    title: "New Order from Aliko Dangote",
    type: "order",
    rid: "",
  },
  {
    id: "12",
    sent: new Date(),
    body: "",
    opened: new Date(),
    status: "opened",
    title: "New Order from Aliko Dangote",
    type: "order",
    rid: "",
  },
];
