import { type Notification as NType } from "@prisma/client";

export const data: NType[] = [
  {
    id: "1",
    read: new Date(),
    body: "",
    on: new Date(),
    status: "sealed",
    title: "New Order from Aliko Dangote",
    type: "order",
  },
  {
    id: "2",
    read: new Date(),
    body: "",
    on: new Date(),
    status: "opened",
    title: "New Order from Aliko Dangote",
    type: "order",
  },
  {
    id: "3",
    read: new Date(),
    body: "",
    on: new Date(),
    status: "sealed",
    title: "New Order from Aliko Dangote",
    type: "order",
  },
  {
    id: "4",
    read: new Date(),
    body: "",
    on: new Date(),
    status: "opened",
    title: "New Order from Aliko Dangote",
    type: "order",
  },
  {
    id: "5",
    read: new Date(),
    body: "",
    on: new Date(),
    status: "sealed",
    title: "New Order from Aliko Dangote",
    type: "order",
  },
  {
    id: "6",
    read: new Date(),
    body: "",
    on: new Date(),
    status: "opened",
    title: "New Order from Aliko Dangote",
    type: "order",
  },
  {
    id: "7",
    read: new Date(),
    body: "",
    on: new Date(),
    status: "sealed",
    title: "New Order from Aliko Dangote",
    type: "order",
  },
  {
    id: "8",
    read: new Date(),
    body: "",
    on: new Date(),
    status: "opened",
    title: "New Order from Aliko Dangote",
    type: "order",
  },
  {
    id: "9",
    read: new Date(),
    body: "",
    on: new Date(),
    status: "sealed",
    title: "New Order from Aliko Dangote",
    type: "order",
  },
  {
    id: "10",
    read: new Date(),
    body: "",
    on: new Date(),
    status: "opened",
    title: "New Order from Aliko Dangote",
    type: "order",
  },
  {
    id: "11",
    read: new Date(),
    body: "",
    on: new Date(),
    status: "sealed",
    title: "New Order from Aliko Dangote",
    type: "order",
  },
  {
    id: "12",
    read: new Date(),
    body: "",
    on: new Date(),
    status: "opened",
    title: "New Order from Aliko Dangote",
    type: "order",
  },
];
